dist: trusty
sudo: required
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libgtest-dev
      
install:
  - pushd ~
  - git clone https://github.com/open-source-parsers/jsoncpp.git
  - pushd jsoncpp
  - cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON 
  - sudo make install
  - popd
  - popd
  - pushd ~
  - git clone https://github.com/warmcat/libwebsockets.git
  - pushd libwebsockets
  - cmake .
  - sudo make install
  - popd
  - popd
  - pushd /usr/src/gtest
  - sudo env "PATH=$PATH" cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - popd
  

script:
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake .
  - cmake --build .
  - ./Tests/execTests
